version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    depends_on:
      - postgres
      - redis
    command: /gunicorn.sh
    env_file: .env

  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .env

  nginx:
    image: nginx
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    command: "nginx -g 'daemon off;'"

  redis:
    image: redis:3.0
